### ISSUE TITLE
hadoop ha 切换失败

### ISSUE THREAD

**Issue by whitelilis** [whitelilis/whitelilis.github.io#1]
zkfc logs:
```
2015-09-24 11:44:44,739 WARN org.apache.hadoop.ha.HealthMonitor: Transport-level exception trying to monitor health of NameNode at hostname1/192.168.10.11:8020: Call From hostname1/192.168.10.11 to hostname1:8020 failed on socket timeout exception: java.net.SocketTimeoutException: 45000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/192.168.10.11:22614 remote=hostname1/192.168.10.11:8020]; For more details see: http://wiki.apache.org/hadoop/SocketTimeout
2015-09-24 11:44:44,740 INFO org.apache.hadoop.ha.HealthMonitor: Entering state SERVICE_NOT_RESPONDING
```
看起来和  https://issues.apache.org/jira/browse/HDFS-9126  一样 

这段代码在 HealthMonitor.java  209 行,  doHealthChecks() 方法, 抛出异常.

说是的连接 8020 rpc 端口超时, 难道什么东西加锁了, 导致 8020 不响应?  也有可能是 zkfc 自己发不出去请求, 自己把自己锁了.

抓 两个 nn 和两个 zkfc 的 jstack 看看;
超时的时候
zkfc: 貌似一直在 sleep, 说明 doHealthChecks() 方法内部不是阻塞执行的.
```
"Health Monitor for NameNode at mainNN.master.adh/10.10.1.201:8020" #27 daemon prio=5 os_prio=0 tid=0x00007fdce920d000 nid=0x1b46 waiting on condition [0x00007fdca9bd4000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.apache.hadoop.ha.HealthMonitor.doHealthChecks(HealthMonitor.java:225)
        at org.apache.hadoop.ha.HealthMonitor.access$600(HealthMonitor.java:48)
        at org.apache.hadoop.ha.HealthMonitor$MonitorDaemon.run(HealthMonitor.java:286)
```
45 秒超时
![image](https://user-images.githubusercontent.com/1090230/34593186-3d1cbc00-f204-11e7-939f-e13e9a51ad96.png)

切换时, 60 秒超时
![image](https://user-images.githubusercontent.com/1090230/34593188-42c7c848-f204-11e7-81b8-047dea51f727.png)

按连接里给的 url , 排查了所有的可能的错误, 都不是.....
关掉 iptables, 还是超时.

看 NN 日志
原来是 8020 服务卡住了
![image](https://user-images.githubusercontent.com/1090230/34593190-4af757fe-f204-11e7-8025-ab2dda85d8f6.png)

NameNodeRpcServer 这个东东被loadEdits() 给锁了.
![image](https://user-images.githubusercontent.com/1090230/34593193-500ae508-f204-11e7-9b93-3a20992314c1.png)

找到相关参数, 调整
```xml
<property>
  <name>ha.health-monitor.rpc-timeout.ms</name>
  <value>45000</value>
  <description>
    Timeout for the actual monitorHealth() calls.
  </description>
</property>

<property>
  <name>ha.failover-controller.new-active.rpc-timeout.ms</name>
  <value>60000</value>
  <description>
    Timeout that the FC waits for the new active to become active
  </description>
</property>
```
测试生效

**Comment by gnuhpc** [comment]
没看明白这个case想表达的意思，这个超时是谁引起的，怎么解决的？

**Comment by whitelilis** [comment]
不切换时， 45 秒超时， 切换时 60 秒超时， 而实际切换时，因为loadEdit() 时间过长（比如在 gc时间过久，比如edit 过大），超过了 60 秒，就挂了。
最终修改参数为：
    ha.health-monitor.rpc-timeout.ms: 120000
    ha.failover-controller.new-active.rpc-timeout.ms: 180000
